#TargetName:Dependencies
#<TAB>commands

Build:OnlineTicketBooking.c
	gcc OnlineTicketBooking.c -o onlineTicketBooking.out

Run:OnlineTicketbooking.out
	./OnlineTicketBooking.out
Clean:
	rm -rf  *.o *.out *.i *.s
	
